### PR TITLE
adding support in geo location of a photo

### PR DESCRIPTION
**Pull request by KingAMS**

### CODE REVIEW

**Comment by opus1269** [comment]
Thanks.

Several people have asked for this.

Looks very clean at first glance.

I'm in the middle of a bunch of changes (working branch). Promisefying everything, improved analytics, other stuff. Touched pretty much everything.  I'll take a look at your changes and see how best to merge it all together.

**Comment by KingAMS** [comment]
10x
Please let me know if u have any q.

**Comment by opus1269** [comment]
I merged in your (modified) changes to the master branch  aa54368

The main changes I made to your stuff:
* Add a simple cache to minimize the calls to the Maps API (also put geo stuff in own file geo.js)
* Cleanup handling of label displays in frame mode
* I also fixed a bug that I introduced not too long ago.

If you get a chance, please take a look and see if I missed anything you intended.

**Comment by opus1269** [comment]
Closed by aa54368

**Comment by KingAMS** [comment]
Looks great ! 10x

**Pull request closed without merging**
